### ISSUE TITLE
Can we use this to fuzz DTLS protocol?

### ISSUE THREAD

**Issue by purninavi** [nccgroup/fuzzowski#15]

**Comment by gry** [comment]
Yes, You can implement a fuzzer for DTLS using fuzzowski. 
You can implement the DTLS fuzzer and if needed to maintain an state between requests, you can use the Variables and Responses. For an example check the mock http fuzzer from the tests: 
https://github.com/nccgroup/fuzzowski/tree/dev/tests/mock_http_server
