### ISSUE TITLE
Can we use this to fuzz DHCP protocol?

### ISSUE THREAD

**Issue by luyj** [nccgroup/fuzzowski#16]

**Comment by gry** [comment]
You can implement the DHCP fuzzer and if needed to maintain an state between requests, you can use the Variables and Responses. For an example check the mock http fuzzer from the tests:
https://github.com/nccgroup/fuzzowski/tree/dev/tests/mock_http_server

Also, check the wiki https://github.com/nccgroup/fuzzowski/wiki , it does not have a lot of info, but it may be enough to get you started :)
