### ISSUE TITLE
Modbus Fuzzer is sending wrong length value

### ISSUE THREAD

**Issue by KaptainH** [nccgroup/fuzzowski#17]
Hi,

First, thanks for all your work ! Such a great tool !
I have an issue when testing modbus fuzzer as the length field is defined with s_word(0x06, name='length')
For example, in the test case 1, the fuzzer is sending b'\x00\x00\x00\x00\x06\x00\xff\x01\x00\x00\x00\x00' instead of b'\x00\x00\x00\x00\x00\x06\xff\x01\x00\x00\x00\x00' resulting a length value of 1536 (\x06\x00) instead of 6 (\x00\x06). All modbus packet are undecoded by the modbus wireshark dissector and discarded from the device because of this wrong length calculation. 
Have you experienced the same issue ?

**Comment by 1modm** [comment]
Hi,

Interesting, try to play with the endian param not sure which one is by default: (LITTLE_ENDIAN: <, BIG_ENDIAN: >)

s_word(0x06, endian='>', name='length') 

Thanks

**Comment by KaptainH** [comment]
This is working with big_endian, default is little_endian.
Thanks !
