### ISSUE TITLE
Session establishment at application level before sending fuzzing requests

### ISSUE THREAD

**Issue by KaptainH** [nccgroup/fuzzowski#21]
Hi guys,

Thanks for this tool :)

Many protocols require multiples valid messages before establishing a session at the application level otherwise any fuzzed messages valid or not will generally respond with the same generic error message.
With fuzzowski, how can you validate thoses handshakes everytime before sending fuzzed messages ?

```
    def requeststofuzz(session: Session) -> None:
       #Here i want to complete handshake messages (i mean static handshake, not fuzzable)
        session.connect(
            s_get('myfirstrequest'),
            s_get('mysecondrequest'),
            callback=mycallback
        )
```

Thanks for your help !
Regards

**Comment by KaptainH** [comment]
Let me explain a little bit more :
I have some OPCUA requests that i want to fuzz separately :
```

    @staticmethod
    def get_requests() -> List[callable]:
        return [
            OPCUA.hello,
            OPCUA.openchannel,
            OPCUA.closechannel,
            OPCUA.createsession,
            OPCUA.activatesession
        ]
```

For the OPCUA.hello standalone case, its ok, i just send the hello messages with mutations like this :

```
    def hello(session: Session) -> None:
        #Only Fuzz the Hello message. 
        session.connect(
            s_get('hello')
        )
```


To fuzz the OPCUA.openchannel, for each test case, i need first to send a static valid OPCUA.hello before sending and OPCUA.openchannel. Here i can do this trick by define a statichello :

```
    def openchannel(session: Session) -> None:
        session.connect(
            # We have to send a valid hello message before fuzzing an openchannel request
            s_get('hellostatic'),  
            s_get('openchannel'),
        )
```

But to fuzz the OPCUA.closechannel, first i need to send a static valid OPCUA.hello then receive the response, then send a valid OPCUA.openchannel and finally i can fuzz the OPCUA.closechannel.
Same thing for the OPCUA.createsession, i need send valid hello --> receive response --> send valid openchannel --> receive response --> send fuzzed createsession. 

Have you and idea of the best way to do that with fuzzowski ? i'm stuck in the definition of the openchannel function because session.connect does not allow me to send more than 2 requests : 
```
    def closechannel (session: Session) -> None:
          # Send a valid hello message and receive response then send a valid openchannel request, receive the response then fuzz the closechannel request

     
```
Thank you : )

Regards

**Comment by gry** [comment]
Hi KaptainH!

You can connect more requests calling several times to session.connect with a path, forming a graph with all the connect calls. Probably not very well explained, sorry! 

I think in this case, you can conect oppenchannel with closechannel like this:

```python
def closechannel (session: Session) -> None:
    # Send a valid hello message and receive response then send a valid openchannel request, receive the response then fuzz the closechannel request
    session.connect(
            s_get('hellostatic'),  
            s_get('openchannel')
        )
    session.connect(
            s_get('openchannel'),  
            s_get('closechannel')
        )
```

That way it will first fuzz hellostatic, then openchannel, and finally closechannel (but you can always just move between the requests in the fuzzing session and go directly to closechannel)

Also, in case you need something from the responses (e.g. some session ID or parameter set by the server that you need to use in next requests) you can use the Response module with s_response, to extract what you need as variables. There is an example using regex (but you can define your own) in this test case: 

https://github.com/nccgroup/fuzzowski/blob/master/tests/mock_http_server/mock_http_fuzzer.py

Hope that helps!

**Comment by KaptainH** [comment]
Hi Mario !

Ok that nice, i did not realize that i could chain requests that way, but now its more clear for me how to build the fuzzing path i need. 
Also, i will probably use s_response to extract OPCUA session variables. 
Thanks for you reply, that helps a lot :)
