### ISSUE TITLE
Error received message but thet test case executed pass

### ISSUE THREAD

**Issue by Bubble-mt** [nccgroup/fuzzowski#24]
When I execute the command line and run testcase:
python -m fuzzowski 127.0.0.1 631 -f ipp -r get_printer_attribs 

I see the received bytes have messge, but test case executed pass without error pop up.
<img width="914" alt="1633685876(1)" src="https://user-images.githubusercontent.com/72586297/136534244-70ae3680-4f13-4093-9689-4d870b3e1a64.png">

**Comment by gry** [comment]
That is the normal behavior, as that is not an error you want flagged as a suspect test case. That is the protocol properly working, detecting an error with the printer name or class. 

Normally we would want to get flagged the protocol crashing, dropping the connection, or even better, crashing or restarting the whole printer or service.

But, if you want to get that information, or flag those errors, you can extend the Response class to get information from the response. Check these classes as examples:

https://github.com/nccgroup/fuzzowski/tree/master/fuzzowski/responses
