### ISSUE TITLE
does fuzzowski support interactive protocol fuzz?

### ISSUE THREAD

**Issue by fr0zenrain** [nccgroup/fuzzowski#25]
in real world, most case need login first,the client send a request, and recv server random seed, then client send again.it seems like fuzzowski not support this scene. may be i need some document,thanks!

**Comment by gry** [comment]
Hi,

Fuzzowski supports stateful fuzzers with the behaviour that you comment using Response objects, but as you comment is not well documented. Please check this example, which performs an HTTP request to get the token that is needed afterwards:

https://github.com/nccgroup/fuzzowski/blob/master/tests/mock_http_server/mock_http_fuzzer.py

Line 60 defines the response and in this case the variable to retrieve (Using HTTPJsonResponse, there are several, including Regex ones)

~~~python
59        # This response takes the JSON parameter "token" of the response and set a variable with it
60        s_response(HTTPJsonResponse, name='token_response', required_vars=['token'], optional_vars=[])
~~~

Line 73 uses the variable set by the response in the new request:

~~~python
73        s_variable('token', value=b'NOTSET')  # Takes the Variable 'token' set by the response of the /token request
~~~
