### ISSUE TITLE
Error adding new fuzzer

### ISSUE THREAD

**Issue by 1modm** [nccgroup/fuzzowski#7]
Hi,

Trying to add a new fuzzer using only bytes and words, the console is not being launched and I'm receiving the next error:

```
$ python -m fuzzowski 10.32.234.36 47808 -p udp -f testFuzzer
[2019-08-14 15:28:05,045]     Info: Using session file: fuzzowski-results/testFuzzer_10.32.234.36_47808_udp_default_d41d8cd98f00b204e9800998ecf8427e.session
Warning: Output is not to a terminal (fd=6).
```

Here you can find the fuzzer example:

```
from typing import List
from .ifuzzer import IFuzzer
from .. import *
from ..sessions import Session

class testFuzzer(IFuzzer):

    name = 'testFuzzer'

    @staticmethod
    def get_requests() -> List[callable]:
        return [testFuzzer.testpacket]

    @staticmethod
    def define_nodes(*args, **kwargs) -> None:
        s_initialize('test_packet')
        #s_string('hola', name='hola')

        if s_block_start("test1"):
            s_byte(0x81, name='test2', fuzzable=False)
            s_byte(0xa, name='test3', fuzzable=False)
            s_word(0x0011, name='test4', fuzzable=False)
        s_block_end()
        if s_block_start("test5"):
            s_byte(0x1, name='version', fuzzable=True)
            s_byte(0x4, name='control', fuzzable=True)
        s_block_end()


    @staticmethod
    def testpacket(session: Session) -> None:
        session.connect(s_get('test_packet'))

```

The console only works if I uncomment the line: #s_string('hola', name='hola'), it seems that it is needed an string to launch the console.

**Comment by gry** [comment]
Hi!

It seems to be a problem with using "if s_block_start()" and "s_block_end()" instead of "with s_block()". I only tested with the last one. While I investigate it, you can use this workaround:

    @staticmethod
    def define_nodes(*args, **kwargs) -> None:
        s_initialize('test_packet')
        # s_string('hola', name='hola')
        
        # if s_block_start("test1"):
        with s_block("test1"):
            s_byte(0x81, name='test2', fuzzable=False)
            s_byte(0xa, name='test3', fuzzable=True)
            s_word(0x0011, name='test4', fuzzable=True)
        # s_block_end()
        with s_block("test5"):
            s_byte(0x1, name='version', fuzzable=True)
            s_byte(0x4, name='control', fuzzable=True)
        # s_block_end()

Hope that helps!

**Comment by 1modm** [comment]
Thanks! it seems to work
